name: hello world test

on:
  push:
    branches:
      - test_action


jobs:
  run_test:
    name: run a simple test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - centos8

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Echo a message
        run: echo 'Hi. This is a test'