name: run a molecule test

on:
  push:
    branches:
      - test_action


jobs:
  run_test:
    name: run a simple test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - centos8

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: setup environment
        run: pip3 install yamllint ansible-lint docker molecule

      - name: run molecule
        run: cd files/test_role; molecule test